### ISSUE TITLE
How to use Signature or User ID to get user's information?

### ISSUE THREAD

**Issue by ZihanChen1995** [wikimedia/mediawiki-api-demos#221]
Hi there, 

I'm a beginner at Wikimedia, and I'm using Wiki API to finish my project. My dataset looks like this:
```
rev_id | comment | timestamp | page_id | page_title | user_id | user_text
-- -- -- -- -- -- -- -- -- -- -- --
352194497 | Welcome   to Wikipedia | 2010-03-26T18:16:48Z | 26709696 | 116.197.206.138 | 8356162 | Mlpearc
```
I'm trying to find some user information of these comment posters. However, I find the "user_text" here is not the user name but the signature. If I use the official API demos ```get_users.py``` to get the information, it turns out the error because some signature have space in it, but usernames are all single word. Like in the code below, I can get the information of Catrope and Bob using ```Catrope|Bob```. But it doesn't work if I use ```Catrope|Bob Ben```, if Bob Ben is Bob's signature.

```
import requests

S = requests.Session()

URL = "https://en.wikipedia.org/w/api.php"

PARAMS = {
    "action": "query",
    "format": "json",
    "list": "users",
    "ususers": "Catrope|Bob",
    "usprop": "blockinfo|groups|editcount|registration|emailable|gender"
}

R = S.get(url=URL, params=PARAMS)
DATA = R.json()

USERS = DATA["query"]["users"]

for u in USERS:
    print(str(u["name"]) + " has " + str(u["editcount"]) + " edits.")

```

So my question is, is there any way we can get user information through the signature using API? And since we also have page_id and user_id here, will this information be helpful? Thank you so much in advance!

**Comment by brendajerop** [comment]
@ZihanChen1995 Using spaces in the `ususers` parameter does not return an error. The error you ran into was because the user `Bob Ben` does not exist. For an existing user(Catrope), the API returned a dictionary like so:
`{'userid': 4587601, 'name': 'Catrope', 'editcount': 377, 'registration': '2007-06-07T16:36:03Z', 'groups': ['*', 'user', 'autoconfirmed'], 'emailable': '', 'gender': 'male'}`

For a non-existent user(Bob Ben), the API returned:
`{'name': 'Bob Ben', 'missing': ''}`

The last line of your code prints out the editcount of a user  and it finds the editcount by looking for the key `editcount` from the dictionary of the API response. This key does not exist in the response of a missing user and that is why you ran into an error.

As for whether the other information you have may be helpful, you may not be able to use it with `API Users` specifically but you can use it with other modules. E.g You may be able to use `page_id` with [API:Move](https://www.mediawiki.org/wiki/API:Move). Please see the [documentation](https://www.mediawiki.org/wiki/API:Main_page) of the API for more information.

**Comment by ZihanChen1995** [comment]
Hi Jerop! Yes, the error is exactly the same as you describe. Now I understand why it happens. I'll check the module that you mentioned. Thank you a lot for your help!
